	minetest.register_tool("rangedweapons:shotfun", {
	stack_max= 1,
	wield_scale = {x=2.0,y=2.0,z=1.75},
		description = "" ..core.colorize("#35cdff","shotgun\n"),
	range = 1,
	inventory_image = "rangedweapons_rifle.png",
RW_powergun_capabilities = {
                automatic_gun = 1,
		power_damage = {fleshy=10,knockback=0},
		power_crit = 8,
		power_critEffc = 2.2,
		power_skill = {"",1},
		
		power_velocity = 23,
		power_accuracy = 40,
		power_cooldown = 0.5,
		power_projectiles = 1,
		power_durability = 2000,
		power_sound = "rangedweapons_laser",
		power_glass_breaking = 1,
		power_door_breaking = 1,
		power_dps = 0,
		power_mob_penetration = 40,
		power_node_penetration = 0,
		power_dps = 0,
		power_consumption = 30,
		power_entity = "rangedweapons:shot_bullet",
		power_visual = "sprite",
		power_texture = "rangedweapons_bullet2.png",
		power_projectile_size = 0.005,
		power_projectiles = 7,
		has_sparks = 0,
		ignites_explosives = 1,
	},
        inventory_image = "rangedweapons_laser_shotgun.png",

})
